### ISSUE TITLE
Add Past Speakers to Website

### ISSUE THREAD

**Issue by VagishVela** [GDG-DevFest-Ohio/devfest-ohio-2023#28]
**Ticket 1: Addition of Past Speakers**
- **Title:** Add Past Speakers to Website.
- **Description:** Create a dedicated page for past speakers sourced from previous material. If available, include their respective talks.
- **Acceptance Criteria:**
  1. New page dedicated to past speakers is accessible.
  2. Page displays speaker names, photos, and brief bios.
  3. Talks from the speakers, if available, are linked/embedded on the page.

**Comment by shrinkray** [comment]
# Found content to reference 
- Will use previous speaker details from the last site

## Digging, 2022 hoverboard: 
- [default-firebase-data.json](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2022/blob/main/docs/default-firebase-data.json)
- [headshots](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2022/tree/main/public/images/people)

## Other useful content
- [Why is it cool to speak at the DevFest](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2022/blob/main/public/data/posts/2017-02-12-c4p.md)
- [Code of Conduct](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2022/blob/main/public/data/coc.md)
- [FAQ](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2022/blob/main/public/data/faq.md)
- [Links to other GDG](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2022/blob/main/public/data/resources.json)s

**Comment by shrinkray** [comment]
this was resolved, closing issue.
