### ISSUE TITLE
Detail Past Conferences

### ISSUE THREAD

**Issue by VagishVela** [GDG-DevFest-Ohio/devfest-ohio-2023#30]
- **Description:** Begin with the previous DevFest. Each conference requires a dedicated page inclusive of photos and available information.
- **Acceptance Criteria:**
  1. Dedicated page for the previous DevFest is created.
  2. Page showcases photos and other related information.
  3. Page navigation for past conferences is intuitive.

**Comment by shrinkray** [comment]
@VagishVela I do not have a working version of the previous site. I am feeling overwhelmed already.

**Comment by VagishVela** [comment]
@shrinkray I think we have the data in the old websites firebase.json or something.

**Comment by shrinkray** [comment]
Some past speakers were added to the site. This request will be closed.
