### ISSUE TITLE
Detail Hackathon Event

### ISSUE THREAD

**Issue by VagishVela** [GDG-DevFest-Ohio/devfest-ohio-2023#37]
- **Description:** Design a page for the hackathon event. Highlight benefits for students.
- **Acceptance Criteria:**
  1. Hackathon page includes event details and schedule.
  2. Page emphasizes the free entry for students.
  3. Include something around “From the organizers who brought you the Falcathon and the DataHack”, I can poke around and provide logos as well.

**Comment by shrinkray** [comment]
This is a stale request.
