### ISSUE TITLE
Differentiate Ohio HackFest & DevFest Logos

### ISSUE THREAD

**Issue by VagishVela** [GDG-DevFest-Ohio/devfest-ohio-2023#38]
- **Description:** Design similar logos but in varying colors for HackFest & DevFest.
- **Acceptance Criteria:**
  1. Two distinct logos are designed.
  2. Both logos retain brand consistency but have color variations.

**Comment by shrinkray** [comment]
@VagishVela 
- We have an Ohio DevFest logo from before. Is this the Devfest logo you reference or do you expect another logo to be created for this event? 
- Is the 'HackFest' logo the same as MLH logo or something different? 
- Assuming the ask for the item above is different from the MLH logo, where will we add the MLH logo? 
- Is it considered a sponsor?

**Comment by shrinkray** [comment]
Created this yesterday ... pill shapes are based on GDG <> art. 

![Hack Ohio Experiment](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2023/assets/732141/7e41c5b9-9582-4583-bb9d-98bb1f51581f)

This took about 4 hrs to complete

**Comment by VagishVela** [comment]
@shrinkray I was originally thinking keeping the same devfest logo and just having a different color for the hackfest. I haven't passed the idea around. Let's try and timebox these, if it seems like a big task we can discuss more.

I like the logo design, only issue is HackOhio is the OSU brand. And I don't know how prominent BGSU wants to be in this. Love the Ohio map behind it!

I think we might need to ask Robert on the MLH question.

**Comment by shrinkray** [comment]
@VagishVela color of this artwork is irrelevant. All graphic/logo work I do is in SVG, and can be assigned via code as such. 

The issue you wrote is confusing because it is asking for work that may already done. What I want you to clear up is whether to use existing logo artwork? Do we need to come up with a replacement for the script Ohio art which is significant to OSU. We've widely used this logo, and I assume it is ours. It was found in the 2019 folder in GDG Ohio Devfest info. 

We need to decide if we have our own pallet or adopt BGSU's.

**Comment by VagishVela** [comment]
@shrinkray Sorry on the confusing aspect of the ticket, I was more thinking of just changing the text and color of the logo from Dev to Hack for the new logo specific to the Hackathon.

**Comment by shrinkray** [comment]
@VagishVela Oh, knowing that would have saved time. Made this, closer to GDG branding while stewing. 

![HackOhioBGSU](https://github.com/GDG-DevFest-Ohio/devfest-ohio-2023/assets/732141/81267f89-1bc0-446e-b452-79cd6b59f7ed)

**Comment by shrinkray** [comment]
@VagishVela Which do you like better, with the date on the right or without on the left? I can work on the date area a little more to make it work better visually, but this is a concept. 

<img width="490" alt="Screenshot 2023-09-03 at 7 48 37 PM" src="https://github.com/GDG-DevFest-Ohio/devfest-ohio-2023/assets/732141/983fc18c-289e-495c-9122-4421895e3b8e">

**Comment by shrinkray** [comment]
@VagishVela Do the images above pass the two criteria?

**Comment by VagishVela** [comment]
I like the left ones, maybe different colors. Otherwise we are gold!

**Comment by shrinkray** [comment]
This event with a hackathon was cancelled
