### ISSUE TITLE
Revamp Home Page with Event Logos

### ISSUE THREAD

**Issue by VagishVela** [GDG-DevFest-Ohio/devfest-ohio-2023#39]
- **Description:** Home page should feature both HackFest & DevFest logos and direct visitors to dedicated pages.
- **Acceptance Criteria:**
  1. Home page showcases both logos prominently.
  2. Clicking on each logo navigates to its event's dedicated page.

**Comment by shrinkray** [comment]
this was for an earlier event that was cancelled.
